baseURL: http://www.ainsuasty.com
title: AINSUASTY
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 20
pygmentsStyle: manni
highlightjsTheme: Github
pygmentsUseClassic: no
pygmentsCodeFences: yes
pygmentsCodeFencesGuessSyntax: yes
enableEmoji: yes
googleAnalytics: "UA-176122758-1"
params:
  author: Andrés Felipe Insuasty Ch.
  avatarurl : "images/Foto_Marca_Personal.jpeg"
  colorScheme: auto
  customCSS: []
  customJS: []
  customSCSS: []
  dateFormat: January 2, 2006
  description: Andrés Insuasty's personal website
  enableTwemoji: yes
  footerContent: Personal Website made with ❤️ R + hugo + Github + Netlify.
  hideColorSchemeToggle: no
  hideCopyright: no
  hideCredits: no
  hideFooter: no
  info: R | Shiny Developer
  keywords: blog,developer,personal
  maxSeeAlsoItems: 5
  rtl: no
  since: 2021
  social:
    - icon: fa fa-github
      name: Github
      url: https://github.com/ainsu23
      weight: 1
    - icon: fa fa-twitter
      name: Twitter
      url: https://twitter.com/Afinsuasty/
      weight: 2
    - icon: fa fa-linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/afinsuasty/
      weight: 3
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  en:
    languageName: ':uk:'
    menu:
      main:
        - name: About
          url: about/
          weight: 1
        - name: 7 goals 2022
          url: 7goals2022/
          weight: 2
        - name: My R world 
          identifier: rworld
          url: rworld/
          weight: 3
        - name: Blog
          url: posts/
          parent: rworld
          weight: 30
        - name: Projects
          url: projects/
          parent: rworld
          weight: 31
        - name: Shiny apps
          url: Shiny/
          parent: rworld
          weight: 32
        - name: learning polish
          url: learning-polish/
          parent: 7 goals 2022 
          weight: 33
        - name: Contact me
          url: contact/
          weight: 4
        - name: resume
          url: resume
          weight: 5
  es:
    languageName: ':es:'
    menu:
      main:
        - name: Blog
          url: post/
          weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true
