baseURL: http://www.ainsuasty.com
title: AINSUASTY
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 20
pygmentsStyle: bw
pygmentsCodeFences: yes
pygmentsCodeFencesGuessSyntax: yes
enableEmoji: yes
params:
  author: Andres Insuasty
  avatarurl = "images/Foto_Marca_Personal.jpeg"
  colorScheme: auto
  commit: https://github.com/luizdepra/hugo-coder/tree/
  csp:
    childsrc: '''self'''
    connectsrc:
      - '''self'''
      - https://www.google-analytics.com
    fontsrc:
      - '''self'''
      - https://fonts.gstatic.com
      - https://cdn.jsdelivr.net/
    formaction: '''self'''
    framesrc: '''self'''
    imgsrc: '''self'''
    objectsrc: '''none'''
    prefetchsrc: '''self'''
    scriptsrc:
      - '''self'''
      - '''unsafe-inline'''
      - https://www.google-analytics.com
    stylesrc:
      - '''self'''
      - '''unsafe-inline'''
      - https://fonts.googleapis.com/
      - https://cdn.jsdelivr.net/
  customCSS: []
  customJS: []
  customSCSS: []
  dateFormat: January 2, 2006
  description: Andres Insuasty's personal website
  enableTwemoji: no
  footerContent: Personal Website made with love from Rstudio cloud + hugo + Github + imagination and hardwork.
  hideColorSchemeToggle: no
  hideCopyright: no
  hideCredits: no
  hideFooter: no
  info: Data Analyst
  keywords: blog,developer,personal
  maxSeeAlsoItems: 5
  rtl: no
  since: 2021
  social:
    - icon: fa fa-github
      name: Github
      url: https://github.com/ainsu23
      weight: 1
    - icon: fa fa-twitter
      name: Twitter
      url: https://twitter.com/Afinsuasty/
      weight: 2
    - icon: fa fa-linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/afinsuasty/
      weight: 3
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  en:
    languageName: ':uk:'
    menu:
      main:
        - name: About
          url: about/
          weight: 1
        - name: Blog
          url: posts/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Contact me
          url: contact/
          weight: 5