baseURL: http://www.ainsuasty.com
title: AINSUASTY
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 20
pygmentsStyle: bw
pygmentsCodeFences: yes
pygmentsCodeFencesGuessSyntax: yes
enableEmoji: yes
googleAnalytics: "UA-176122758-1"
params:
  author: Andres Insuasty
  avatarurl : "images/Foto_Marca_Personal.jpeg"
  colorScheme: auto
  customCSS: []
  customJS: []
  customSCSS: []
  dateFormat: January 2, 2006
  description: Andres Insuasty's personal website
  enableTwemoji: yes
  footerContent: Personal Website made with ❤️ from Rstudio cloud + hugo + Github + imagination and hardwork.
  hideColorSchemeToggle: no
  hideCopyright: no
  hideCredits: no
  hideFooter: no
  info: Data Analyst
  keywords: blog,developer,personal
  maxSeeAlsoItems: 5
  rtl: no
  since: 2021
  social:
    - icon: fa fa-github
      name: Github
      url: https://github.com/ainsu23
      weight: 1
    - icon: fa fa-twitter
      name: Twitter
      url: https://twitter.com/Afinsuasty/
      weight: 2
    - icon: fa fa-linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/afinsuasty/
      weight: 3
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  en:
    languageName: ':uk:'
    menu:
      main:
        - name: About
          url: about/
          weight: 1
        - name: Blog
          url: posts/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Contact me
          url: contact/
          weight: 4
        - name: cv
          url: cv/
          weight: 5
  es:
    languageName: ':es:'
    menu:
      main:
        - name: Blog
          url: post/
          weight: 1
