---
title: Reglas basicas de Git
author: Andrés Felipe Insuasty
date: '2021-08-10'
slug: []
categories:
  - Git
tags:
  - Git
authors: []
description: ''
externalLink: ''
series: []
---

# Reglas en Git {style="color:red"}

### Regla \#1: {style="color:blue"}

*El master debe siempre estar actualizado con upstream/master. En este, no se pueden hacer cambios ni commits. Mantener actualizado siguiente el paso \#1.*

[***En caso de saltarse la Regla \#1, realizar paso \#3.***]{.ul}

### Regla \#2: {style="color:blue"}

Se debe abrir una rama por cada issue, en esta rama se realiza el paso \#2.

### Regla \#3: {style="color:blue"}

Seguir el conventional commits del siguiente link:

[\<https://www.conventionalcommits.org/en/v1.0.0/\>](https://www.conventionalcommits.org/en/v1.0.0/){.uri}

## Paso \#1: Traer el trabajo de otro colaborador

**git remote -v :** bifurcaciones conectadas

**git remote add *`Colaborador`*[enlace_bifurcacion]{.ul} :** Adiciona bifurcación a mi repositorio

**git fetch *`Colaborador`* :** Busco cambios mi repositorio con el repositorio del colaborador

**git merge *`Colaborador`* /rama :** Trae los cambios de la rama sin quitar mi trabajo realizado

**git rebase** ***`upstream`*****/master :** Trae los cambios del upstream/master eliminando mis cambios realizados

## **Paso \#2: Cargar modificaciones a bifurcación**

Una vez realizados los cambios:

**git status :** Se revisa los cambios realizados.

**git add `ruta cambio` :** Se adiciona el cambio a realizar commit

**git commit, `enter`, `i` :** realizar comentario de acuerdo a conventional commits, no olvidar referenciar el número del caso. **para salir:** `esc : x`

**git push:** realiza el push a la bifurcación

**Pull request en github:** para realizar

## Paso \#3: GIT RESET (might be dangerous)

Permite volver commits en el tiempo, se puede perder la información dependiendo de como se escriba el git reset.

-   git whatchanged: Muestra los commits realizados, de aquí se debe tomar el \#id del commit al que se requiere devolver.

-   git reset --hard \#idcommit: devuelve a la rama con ese commit perdiendo todo lo después realizado.

-   git push -f: fuerza cambios con un push
